name: TypeScript Package

on:
  push:
    branches: [ master, ts_py ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./chatmix-ts
      run: npm ci
    - name: Build
      working-directory: ./chatmix-ts
      run: npm run build
    - name: Test
      working-directory: ./chatmix-ts
      run: npm test
